spring:
  liquibase:
    change-log: classpath:migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/book1
    username: postgres
    password: linh2002
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  i18n:
    resources:
      - classpath:clean-architecture-service/message
